# Generated by Django 5.2.7 on 2025-10-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('preco', models.FloatField()),
                ('categoria', models.CharField()),
            ],
        ),
    ]
