# Generated by Django 5.2.7 on 2025-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('descricao', models.TextField()),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
